apiVersion: v1
kind: Service
metadata:
  name: ambassador-generator
  namespace: ambassador
spec:
  ports:
    - name: http
      port: 81
      targetPort: 8081
  selector:
    app: ambassador-generator